package net.jma.eventos;

public enum Evento_Acciones {

	SIN_ACCION, LOGIN, REGISTRO_USUARIO, 
	NUEVA_LISTA, ICONO_LISTA, ICONO_LISTA_GALERIA, ICONO_LISTA_CAMARA, GRABAR_NUEVA_LISTA, 
	CARGA_PRODUCTOS_CATEGORIA, SELECCION_KILOS, SUBE_UNIDADES, BAJA_UNIDADES, NECESITO_TENGO, 
	ICONO_CATEGORIA, GRABAR_NUEVA_CATEGORIA, DIALOGO_SELECCION_CATEGORIA, ADD_PRODUCTO_CATEGORIA, 
	DIALOGO_ADD_PRODUCTO, ELIMINAR_PRODUCTO, ELIMINAR_LISTA, ELIMINAR_CATEGORIA, 
	COMPARTIR_LISTA;
	
}
